config/routes.rb
SecondOpinion::Application.routes.draw do
  
  root to: "static#landing"
  get "info", to: "static#info"
  get "landing", to: "static#landing"
  resources :quizzes

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  attr_accessible :answers, :questions, :result, :score
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def info
  end

  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecondOpinion</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
</head>
<body>
	<%= link_to_unless_current "Landing", info_path %>
	<%= link_to_unless_current "Info", landing_path %>

<%= yield %>

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

app/views/quizzes/index.html.erb
<a href="#" class="btn btn-success btn-large"><i class=icon-ok></i> </a>
<a href="#" class="btn btn-danger btn-large"><i class=icon-remove></i> </a>
<a href="#" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-ok"></span> </a>
<a href="#" class="btn btn-lg btn-danger"><span class="glyphicon glyphicon-remove"></span> </a>